const formsDataStructure = {
    wholesaling: {
        arv: '',
        repairCost: '',
        hedgeExpense: '',
        closingCost: '',
        monthlyHoldingCost: '',
        repairPeriod: '',
        marketingCost: '',
        sellingCost: '',

    },
    purchase: {
        arv: '',
        estPurchasePrice: '',
        propSqft: '',
        costSqft: '',
        repairCost: '',
        hedgeExpense: '',
        repairPeriod: '',
        monthlyHoldingCost: '',
        closingCost: '',
        propertyInsurance: '',
        propertyTax: '',
        hoa: '',
    },
    lease: {
        salesPrice: '',
        optionPayment: '',
        monthlyRental: '',
        monthlyCredit: '',
        leaseTerm: '',
    },
    seller: {
        arv: '',
        estPurchasePrice: '',
        propSqft: '',
        costSqft: '',
        repairCost: '',
        hedgeExpense: '',
        repairPeriod: '',
        monthlyHoldingCost: '',
        closingCost: '',
        propertyInsurance: '',
        propertyTax: '',
        hoa: '',
        loanAmount: '',
        downPayment: '',
        interestRate: '',
        amortizationTerm: '',
        balloonTerm: '',
        monthlyPayment: '',
    },
  };
  
  export default formsDataStructure;
  